[2024-10-22T11:19:10.991+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-22T11:19:11.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-10-21T13:39:55.312986+00:00 [queued]>
[2024-10-22T11:19:11.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-10-21T13:39:55.312986+00:00 [queued]>
[2024-10-22T11:19:11.140+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-22T11:19:11.214+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-10-21 13:39:55.312986+00:00
[2024-10-22T11:19:11.233+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2024-10-21T13:39:55.312986+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpx0mz6c3l']
[2024-10-22T11:19:11.244+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask stream_data_from_api
[2024-10-22T11:19:11.245+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=671) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-22T11:19:11.247+0000] {standard_task_runner.py:64} INFO - Started process 672 to run task
[2024-10-22T11:19:11.389+0000] {task_command.py:426} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2024-10-21T13:39:55.312986+00:00 [running]> on host bdd5421c2cdf
[2024-10-22T11:19:11.586+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T13:39:55.312986+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-21T13:39:55.312986+00:00'
[2024-10-22T11:19:11.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-22T11:19:12.105+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:19:12.106+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-10-22T11:19:12.108+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:19:12.109+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:19:12.156+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:19:12.158+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:19:12.159+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:19:12.208+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:19:12.209+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:19:12.210+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:19:12.212+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-22T11:19:12.213+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 44, in stream_data
    producer = KafkaProducer(bootstrap_servers='localhost:9092', max_block_ms=5000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 902, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-22T11:19:12.240+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, run_id=manual__2024-10-21T13:39:55.312986+00:00, execution_date=20241021T133955, start_date=20241022T111911, end_date=20241022T111912
[2024-10-22T11:19:12.297+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task stream_data_from_api (NoBrokersAvailable; 672)
[2024-10-22T11:19:12.317+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-22T11:19:12.371+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T11:19:12.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
