[2024-10-23T12:58:02.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-23T12:58:03.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-22T00:00:00+00:00 [queued]>
[2024-10-23T12:58:03.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-22T00:00:00+00:00 [queued]>
[2024-10-23T12:58:03.242+0000] {taskinstance.py:2306} INFO - Starting attempt 9 of 9
[2024-10-23T12:58:03.353+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-10-22 00:00:00+00:00
[2024-10-23T12:58:03.388+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2024-10-22T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpitu2gqgz']
[2024-10-23T12:58:03.406+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask stream_data_from_api
[2024-10-23T12:58:03.415+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=772) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-23T12:58:03.418+0000] {standard_task_runner.py:64} INFO - Started process 773 to run task
[2024-10-23T12:58:03.622+0000] {task_command.py:426} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-22T00:00:00+00:00 [running]> on host 99d2c9a4153a
[2024-10-23T12:58:03.951+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-22T00:00:00+00:00'
[2024-10-23T12:58:03.956+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-23T12:58:04.523+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv6 ('::1', 9093, 0, 0)]>: connecting to localhost:9093 [('::1', 9093, 0, 0) IPv6]
[2024-10-23T12:58:04.524+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-10-23T12:58:04.526+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv6 ('::1', 9093, 0, 0)]> returned error 111. Disconnecting.
[2024-10-23T12:58:04.526+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv6 ('::1', 9093, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-23T12:58:04.574+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv6 ('::1', 9093, 0, 0)]>: connecting to localhost:9093 [('::1', 9093, 0, 0) IPv6]
[2024-10-23T12:58:04.576+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv6 ('::1', 9093, 0, 0)]> returned error 111. Disconnecting.
[2024-10-23T12:58:04.576+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv6 ('::1', 9093, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-23T12:58:04.626+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv4 ('127.0.0.1', 9093)]>: connecting to localhost:9093 [('127.0.0.1', 9093) IPv4]
[2024-10-23T12:58:04.627+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv4 ('127.0.0.1', 9093)]> returned error 111. Disconnecting.
[2024-10-23T12:58:04.628+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9093 <connecting> [IPv4 ('127.0.0.1', 9093)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-23T12:58:04.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-23T12:58:04.631+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 44, in stream_data
    producer = KafkaProducer(bootstrap_servers='localhost:9093', max_block_ms=5000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 902, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-23T12:58:04.676+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, run_id=scheduled__2024-10-22T00:00:00+00:00, execution_date=20241022T000000, start_date=20241023T125803, end_date=20241023T125804
[2024-10-23T12:58:04.730+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 122 for task stream_data_from_api (NoBrokersAvailable; 773)
[2024-10-23T12:58:04.774+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-23T12:58:04.841+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T12:58:04.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
